spring.application.name=filepilot-ai

spring.ai.openai.api-key=${OPENAI_API_KEY}

logging.level.org.springframework.ai.chat.client.advisor=DEBUG
server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springframework.web=DEBUG

spring.ai.mcp.client.stdio.servers-configuration=classpath:servers-configuration.json
